### ISSUE TITLE
USB attacks menu loops through options

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/nethunter-utils#13]
Currently the USB attack options menu does not execute any attacks when given either 1 or 2 (common passwords or 4 digit pin attacks) but instead loops back to the number 10 menu (where you either confirm a dictionary attack or exit to main menu).

**Comment by binkybear** [comment]
@thesle3p: We are phasing out kalimenu (I think thats what you are talking about).  We will eventually integrate something similar into app.

**Comment by jmingov** [comment]
Agree, this can be closed. @offensive-security

**Comment by offensive-security** [comment]
Closed.
